/**
 * Stopword lists sourced from NLTK and spaCy, supplemented with
 * curated lists for Ancient Greek, Latin, and Old French.
 *
 * All words are in normalized form (lowercase, no combining marks)
 * to match the output of preprocess.ts.
 */

const STOPWORDS: Record<string, string[]> = {
  // French (504 words)
  fr: [
    'a', 'abord', 'afin', 'ah', 'ai', 'aie', 'aient', 'aies', 'ainsi', 'ait', 'allaient', 'allons',
    'alors', 'anterieur', 'anterieure', 'anterieures', 'apres', 'as', 'assez', 'attendu', 'au',
    'aupres', 'auquel', 'aura', 'aurai', 'auraient', 'aurais', 'aurait', 'auras', 'aurez', 'auriez',
    'aurions', 'aurons', 'auront', 'aussi', 'autre', 'autrement', 'autres', 'autrui', 'aux',
    'auxquelles', 'auxquels', 'avaient', 'avais', 'avait', 'avant', 'avec', 'avez', 'aviez',
    'avions', 'avoir', 'avons', 'ayant', 'ayante', 'ayantes', 'ayants', 'ayez', 'ayons', 'bas',
    'basee', 'bat', 'c', 'ca', 'car', 'ce', 'ceci', 'cela', 'celle', 'celleci', 'cellela', 'celles',
    'cellesci', 'cellesla', 'celui', 'celuici', 'celuila', 'cent', 'cependant', 'certain',
    'certaine', 'certaines', 'certains', 'certes', 'ces', 'cet', 'cette', 'ceux', 'ceuxci', 'ceuxla',
    'chacun', 'chacune', 'chaque', 'chez', 'ci', 'cinq', 'cinquantaine', 'cinquante', 'cinquantieme',
    'cinquieme', 'combien', 'comme', 'comment', 'compris', 'concernant', 'd', 'da', 'dans', 'de',
    'debout', 'dedans', 'dehors', 'deja', 'dela', 'depuis', 'derriere', 'des', 'desormais',
    'desquelles', 'desquels', 'dessous', 'dessus', 'deux', 'deuxieme', 'deuxiemement', 'devant',
    'devers', 'devra', 'different', 'differente', 'differentes', 'differents', 'dire', 'directe',
    'directement', 'dit', 'dite', 'dits', 'divers', 'diverse', 'diverses', 'dix', 'dixhuit',
    'dixieme', 'dixneuf', 'dixsept', 'doit', 'doivent', 'donc', 'dont', 'douze', 'douzieme', 'du',
    'duquel', 'durant', 'effet', 'egalement', 'eh', 'elle', 'ellememe', 'elles', 'ellesmemes', 'en',
    'encore', 'enfin', 'entre', 'envers', 'environ', 'es', 'est', 'et', 'etaient', 'etais', 'etait',
    'etant', 'etante', 'etantes', 'etants', 'etc', 'ete', 'etee', 'etees', 'etes', 'etiez', 'etions',
    'etre', 'eu', 'eue', 'eues', 'eumes', 'eurent', 'eus', 'eusse', 'eussent', 'eusses', 'eussiez',
    'eussions', 'eut', 'eutes', 'eux', 'euxmemes', 'exactement', 'excepte', 'facon', 'fais',
    'faisaient', 'faisant', 'fait', 'feront', 'font', 'fumes', 'furent', 'fus', 'fusse', 'fussent',
    'fusses', 'fussiez', 'fussions', 'fut', 'futes', 'gens', 'ha', 'he', 'hem', 'hep', 'hi', 'ho',
    'hormis', 'hors', 'hou', 'houp', 'hue', 'hui', 'huit', 'huitieme', 'i', 'il', 'ils', 'importe',
    'j', 'je', 'jusqu', 'jusque', 'juste', 'l', 'la', 'laisser', 'laquelle', 'le', 'lequel', 'les',
    'lesquelles', 'lesquels', 'leur', 'leurs', 'longtemps', 'lors', 'lorsque', 'lui', 'luimeme', 'm',
    'ma', 'maint', 'maintenant', 'mais', 'malgre', 'me', 'meme', 'memes', 'merci', 'mes', 'mien',
    'mienne', 'miennes', 'miens', 'mille', 'moi', 'moimeme', 'moindres', 'moins', 'mon', 'n', 'na',
    'ne', 'neanmoins', 'neuvieme', 'ni', 'nombreuses', 'nombreux', 'nos', 'notamment', 'notre',
    'notres', 'nous', 'nousmemes', 'nouveau', 'nul', 'o', 'on', 'ont', 'onze', 'onzieme', 'or', 'ou',
    'ouias', 'ouste', 'outre', 'ouvert', 'ouverte', 'ouverts', 'par', 'parce', 'parfois', 'parle',
    'parlent', 'parler', 'parmi', 'partant', 'pas', 'pendant', 'pense', 'permet', 'personne', 'peu',
    'peut', 'peuvent', 'peux', 'plus', 'plusieurs', 'plutot', 'possible', 'possibles', 'pour',
    'pourquoi', 'pourrais', 'pourrait', 'pouvait', 'prealable', 'precisement', 'premier', 'premiere',
    'premierement', 'pres', 'procedant', 'proche', 'pu', 'puis', 'puisque', 'qu', 'quand', 'quant',
    'quantasoi', 'quarante', 'quatorze', 'quatre', 'quatrevingt', 'quatrieme', 'quatriemement',
    'que', 'quel', 'quelconque', 'quelle', 'quelles', 'quelque', 'quelques', 'quelquun', 'quels',
    'qui', 'quiconque', 'quinze', 'quoi', 'quoique', 'relative', 'relativement', 'rend', 'rendre',
    'restant', 'reste', 'restent', 'retour', 'revoici', 'revoila', 's', 'sa', 'sait', 'sans', 'sauf',
    'se', 'seize', 'selon', 'semblable', 'semblaient', 'semble', 'semblent', 'sent', 'sept',
    'septieme', 'sera', 'serai', 'seraient', 'serais', 'serait', 'seras', 'serez', 'seriez',
    'serions', 'serons', 'seront', 'ses', 'seul', 'seule', 'seulement', 'seules', 'seuls', 'si',
    'sien', 'sienne', 'siennes', 'siens', 'sinon', 'six', 'sixieme', 'soi', 'soient', 'soimeme',
    'sois', 'soit', 'soixante', 'sommes', 'son', 'sont', 'sous', 'souvent', 'soyez', 'soyons',
    'specifique', 'specifiques', 'stop', 'suffisant', 'suffisante', 'suffit', 'suis', 'suit',
    'suivant', 'suivante', 'suivantes', 'suivants', 'suivre', 'sur', 'surtout', 't', 'ta', 'tant',
    'te', 'tel', 'telle', 'tellement', 'telles', 'tels', 'tenant', 'tend', 'tenir', 'tente', 'tes',
    'tien', 'tienne', 'tiennes', 'tiens', 'toi', 'toimeme', 'ton', 'touchant', 'toujours', 'tous',
    'tout', 'toute', 'toutes', 'treize', 'trente', 'tres', 'trois', 'troisieme', 'troisiemement',
    'tu', 'un', 'une', 'unes', 'uns', 'va', 'vais', 'vas', 've', 'vers', 'via', 'vingt', 'voici',
    'voila', 'vont', 'vos', 'votre', 'votres', 'vous', 'vousmemes', 'vu', 'y',
  ],
  // Old French (136 words)
  fro: [
    'a', 'ai', 'ainc', 'ains', 'ainz', 'al', 'apres', 'as', 'aus', 'autre', 'autres', 'avec',
    'aveuc', 'avez', 'avoir', 'avoit', 'avons', 'bien', 'car', 'ce', 'cele', 'ceo', 'cest', 'ceste',
    'chez', 'cil', 'co', 'com', 'comme', 'contre', 'cui', 'de', 'del', 'des', 'devant', 'dire',
    'dist', 'dit', 'donc', 'dont', 'e', 'ele', 'eles', 'els', 'en', 'entre', 'ert', 'est', 'estre',
    'et', 'faire', 'fait', 'fu', 'furent', 'fust', 'i', 'icele', 'icest', 'il', 'ja', 'je', 'jeo',
    'jo', 'l', 'la', 'le', 'les', 'li', 'lor', 'lors', 'lui', 'ma', 'mais', 'me', 'mes', 'mie',
    'molt', 'mon', 'moult', 'mout', 'mult', 'n', 'ne', 'ni', 'nos', 'nostre', 'o', 'od', 'onques',
    'ont', 'or', 'ore', 'orent', 'ot', 'ou', 'par', 'pas', 'plus', 'point', 'por', 'pur', 'qu',
    'quand', 'quant', 'que', 'qui', 'quoi', 'sa', 'sans', 'sanz', 'se', 'ses', 'seur', 'si', 'son',
    'sont', 'sur', 'ta', 'tant', 'te', 'tes', 'ton', 'tot', 'tote', 'totes', 'tout', 'toz', 'tres',
    'tu', 'un', 'une', 'unes', 'uns', 'vers', 'vos', 'vostre',
  ],
  // English (378 words)
  en: [
    'a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'ain', 'all',
    'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst',
    'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere',
    'are', 'aren', 'arent', 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become',
    'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside',
    'besides', 'between', 'beyond', 'both', 'bottom', 'but', 'by', 'ca', 'call', 'can', 'cannot',
    'could', 'couldn', 'couldnt', 'd', 'did', 'didn', 'didnt', 'do', 'does', 'doesn', 'doesnt',
    'doing', 'don', 'done', 'dont', 'down', 'due', 'during', 'each', 'eight', 'either', 'eleven',
    'else', 'elsewhere', 'empty', 'enough', 'even', 'ever', 'every', 'everyone', 'everything',
    'everywhere', 'except', 'few', 'fifteen', 'fifty', 'first', 'five', 'for', 'former', 'formerly',
    'forty', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had', 'hadn', 'hadnt',
    'has', 'hasn', 'hasnt', 'have', 'haven', 'havent', 'having', 'he', 'hed', 'hell', 'hence', 'her',
    'here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers', 'herself', 'hes', 'him', 'himself',
    'his', 'how', 'however', 'hundred', 'i', 'id', 'if', 'ill', 'im', 'in', 'indeed', 'into', 'is',
    'isn', 'isnt', 'it', 'itd', 'itll', 'its', 'itself', 'ive', 'just', 'keep', 'last', 'latter',
    'latterly', 'least', 'less', 'll', 'm', 'ma', 'made', 'make', 'many', 'may', 'me', 'meanwhile',
    'might', 'mightn', 'mightnt', 'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much',
    'must', 'mustn', 'mustnt', 'my', 'myself', 'name', 'namely', 'needn', 'neednt', 'neither',
    'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not',
    'nothing', 'now', 'nowhere', 'nt', 'o', 'of', 'off', 'often', 'on', 'once', 'one', 'only',
    'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own',
    'part', 'per', 'perhaps', 'please', 'put', 'quite', 'rather', 're', 'really', 'regarding', 's',
    'same', 'say', 'see', 'seem', 'seemed', 'seeming', 'seems', 'serious', 'several', 'shan',
    'shant', 'she', 'shed', 'shell', 'shes', 'should', 'shouldn', 'shouldnt', 'shouldve', 'show',
    'side', 'since', 'six', 'sixty', 'so', 'some', 'somehow', 'someone', 'something', 'sometime',
    'sometimes', 'somewhere', 'still', 'such', 't', 'take', 'ten', 'than', 'that', 'thatll', 'the',
    'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby',
    'therefore', 'therein', 'thereupon', 'these', 'they', 'theyd', 'theyll', 'theyre', 'theyve',
    'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to',
    'together', 'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'under', 'unless',
    'until', 'up', 'upon', 'us', 'used', 'using', 'various', 've', 'very', 'via', 'was', 'wasn',
    'wasnt', 'we', 'wed', 'well', 'were', 'weren', 'werent', 'weve', 'what', 'whatever', 'when',
    'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon',
    'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose',
    'why', 'will', 'with', 'within', 'without', 'won', 'wont', 'would', 'wouldn', 'wouldnt', 'y',
    'yet', 'you', 'youd', 'youll', 'your', 'youre', 'yours', 'yourself', 'yourselves', 'youve',
  ],
  // Latin (203 words)
  la: [
    'ab', 'ac', 'ad', 'adhuc', 'aliqui', 'aliquis', 'an', 'ante', 'apud', 'at', 'atque', 'aut',
    'autem', 'contra', 'cui', 'cuius', 'cum', 'cur', 'de', 'deinde', 'dum', 'ea', 'eae', 'eam',
    'earum', 'eas', 'ego', 'ei', 'eis', 'eius', 'enim', 'eo', 'eorum', 'eos', 'erant', 'erat',
    'ergo', 'es', 'esse', 'essent', 'esset', 'est', 'et', 'etiam', 'etsi', 'eum', 'ex', 'fio',
    'fuerit', 'fuerunt', 'fuisse', 'fuisset', 'fuit', 'hac', 'hae', 'haec', 'hanc', 'harum', 'has',
    'haud', 'hi', 'hic', 'his', 'hoc', 'horum', 'hos', 'huic', 'huius', 'hunc', 'iam', 'id', 'idem',
    'igitur', 'ii', 'iis', 'illa', 'illae', 'illam', 'illarum', 'illas', 'ille', 'illi', 'illis',
    'illius', 'illo', 'illorum', 'illos', 'illud', 'illum', 'in', 'infra', 'inter', 'interim',
    'ipsa', 'ipsam', 'ipse', 'ipsi', 'ipsius', 'ipso', 'ipsum', 'is', 'ita', 'itaque', 'magis', 'me',
    'mea', 'mei', 'meum', 'meus', 'mihi', 'modo', 'mox', 'nam', 'ne', 'nec', 'necque', 'neque',
    'nisi', 'nobis', 'non', 'nos', 'noster', 'nostra', 'nostri', 'nostrum', 'o', 'ob', 'omne',
    'omnes', 'omnia', 'omnibus', 'omnis', 'per', 'possum', 'post', 'praeter', 'pro', 'propter',
    'qua', 'quae', 'quam', 'quare', 'quarum', 'quas', 'quem', 'qui', 'quia', 'quibus', 'quicumque',
    'quid', 'quidem', 'quilibet', 'quis', 'quisnam', 'quisquam', 'quisque', 'quisquis', 'quo',
    'quod', 'quoniam', 'quoque', 'quorum', 'quos', 'se', 'sed', 'seu', 'si', 'sibi', 'sic', 'sine',
    'sint', 'sit', 'sive', 'sua', 'sub', 'sui', 'sum', 'sunt', 'super', 'suum', 'suus', 'tam',
    'tamen', 'te', 'tibi', 'trans', 'tu', 'tua', 'tui', 'tum', 'tuum', 'tuus', 'ubi', 'uel', 'uero',
    'ut', 'vel', 'vero', 'vester', 'vestra', 'vestri', 'vobis', 'vos',
  ],
  // Ancient Greek (235 words)
  grc: [
    'α', 'αι', 'αις', 'αλλ', 'αλλα', 'αλλη', 'αλλο', 'αλλοι', 'αλλος', 'αλλων', 'αν', 'ανα',
    'αντι', 'απο', 'αρα', 'ας', 'αυτα', 'αυται', 'αυταις', 'αυτας', 'αυτη', 'αυτην', 'αυτης', 'αυτο',
    'αυτοι', 'αυτοις', 'αυτον', 'αυτος', 'αυτου', 'αυτους', 'αυτω', 'αυτων', 'γαρ', 'γε', 'γενεσθαι',
    'γιγνεται', 'γιγνομαι', 'δε', 'δη', 'δια', 'εαν', 'εγενετο', 'εγω', 'ει', 'ειμι', 'ειναι',
    'ειπε', 'ειπεν', 'ειπον', 'εις', 'εισι', 'εισιν', 'ειχε', 'ειχεν', 'εκ', 'εκεινα', 'εκειναι',
    'εκεινη', 'εκεινην', 'εκεινης', 'εκεινο', 'εκεινοι', 'εκεινον', 'εκεινος', 'εκεινου', 'εκεινω',
    'εκεινων', 'ελεγε', 'ελεγεν', 'εμε', 'εμοι', 'εμου', 'εν', 'ενθα', 'εξ', 'επει', 'επειδη', 'επι',
    'εποιησε', 'εσμεν', 'εστε', 'εστι', 'εστιν', 'εσχε', 'ετι', 'εφη', 'εχει', 'εχειν', 'εχω',
    'εχων', 'η', 'ηδη', 'ημας', 'ημεις', 'ημεν', 'ημιν', 'ημων', 'ην', 'ηπερ', 'ης', 'ησαν', 'ησθα',
    'ητις', 'ινα', 'και', 'κατα', 'λεγει', 'λεγω', 'μαλιστα', 'μαλλον', 'με', 'μεν', 'μετα', 'μη',
    'μηδε', 'μηδεις', 'μηδεν', 'μητε', 'μοι', 'μου', 'νυν', 'ο', 'οι', 'οις', 'ον', 'οπερ', 'οπως',
    'ος', 'οσπερ', 'οστις', 'οτε', 'οτι', 'ου', 'ουδε', 'ουδεις', 'ουδεν', 'ουκ', 'ουν', 'ους',
    'ουσα', 'ουτε', 'ουτοι', 'ουτος', 'ουτω', 'ουτως', 'ουχ', 'παν', 'παντα', 'παντας', 'παντες',
    'παντι', 'παντος', 'παντων', 'παρα', 'πας', 'πασα', 'πασαι', 'πασαν', 'πασας', 'πασης', 'πασι',
    'περ', 'περι', 'ποιει', 'ποιεω', 'πολλα', 'πολλη', 'πολλοι', 'πολλων', 'πολυ', 'πολυς', 'ποτε',
    'που', 'πριν', 'προ', 'προς', 'πως', 'σε', 'σοι', 'σου', 'συ', 'συν', 'σφας', 'σφεις', 'σφισι',
    'σφων', 'τα', 'ταις', 'τας', 'ταυτα', 'ταυταις', 'ταυτη', 'ταυτην', 'ταυτης', 'τε', 'τη', 'την',
    'της', 'τι', 'τινα', 'τινας', 'τινες', 'τινι', 'τινος', 'τινων', 'τις', 'τισι', 'το', 'τοι',
    'τοις', 'τον', 'του', 'τους', 'τουτο', 'τουτοις', 'τουτον', 'τουτου', 'τουτω', 'τουτων', 'τω',
    'των', 'υμας', 'υμεις', 'υμιν', 'υμων', 'υπερ', 'υπο', 'φημι', 'φησι', 'φησιν', 'ω', 'ων', 'ως',
    'ωσπερ', 'ωστε',
  ],
  // German (559 words)
  de: [
    'a', 'ab', 'aber', 'ach', 'acht', 'achte', 'achten', 'achter', 'achtes', 'ag', 'alle',
    'allein', 'allem', 'allen', 'aller', 'allerdings', 'alles', 'allgemeinen', 'als', 'also', 'am',
    'an', 'ander', 'andere', 'anderem', 'anderen', 'anderer', 'anderes', 'anderm', 'andern',
    'anderr', 'anders', 'auch', 'auf', 'aus', 'ausser', 'ausserdem', 'außer', 'außerdem', 'bald',
    'bei', 'beide', 'beiden', 'beim', 'beispiel', 'bekannt', 'bereits', 'besonders', 'besser',
    'besten', 'bin', 'bis', 'bisher', 'bist', 'da', 'dabei', 'dadurch', 'dafur', 'dagegen', 'daher',
    'dahin', 'dahinter', 'damals', 'damit', 'danach', 'daneben', 'dank', 'dann', 'daran', 'darauf',
    'daraus', 'darf', 'darfst', 'darin', 'daruber', 'darum', 'darunter', 'das', 'dasein', 'daselbst',
    'dass', 'dasselbe', 'davon', 'davor', 'dazu', 'dazwischen', 'daß', 'dein', 'deine', 'deinem',
    'deinen', 'deiner', 'deines', 'dem', 'dementsprechend', 'demgegenuber', 'demgemass', 'demgemaß',
    'demselben', 'demzufolge', 'den', 'denen', 'denn', 'denselben', 'der', 'deren', 'derer',
    'derjenige', 'derjenigen', 'dermassen', 'dermaßen', 'derselbe', 'derselben', 'des', 'deshalb',
    'desselben', 'dessen', 'deswegen', 'dich', 'die', 'diejenige', 'diejenigen', 'dies', 'diese',
    'dieselbe', 'dieselben', 'diesem', 'diesen', 'dieser', 'dieses', 'dir', 'doch', 'dort', 'drei',
    'drin', 'dritte', 'dritten', 'dritter', 'drittes', 'du', 'durch', 'durchaus', 'durfen', 'durft',
    'durfte', 'durften', 'eben', 'ebenso', 'ehrlich', 'eigen', 'eigene', 'eigenen', 'eigener',
    'eigenes', 'ein', 'einander', 'eine', 'einem', 'einen', 'einer', 'eines', 'einig', 'einige',
    'einigem', 'einigen', 'einiger', 'einiges', 'einmal', 'einmaleins', 'elf', 'en', 'ende',
    'endlich', 'entweder', 'er', 'erst', 'erste', 'ersten', 'erster', 'erstes', 'es', 'etwa',
    'etwas', 'euch', 'euer', 'eure', 'eurem', 'euren', 'eurer', 'eures', 'fruher', 'funf', 'funfte',
    'funften', 'funfter', 'funftes', 'fur', 'gab', 'ganz', 'ganze', 'ganzen', 'ganzer', 'ganzes',
    'gar', 'gedurft', 'gegen', 'gegenuber', 'gehabt', 'gehen', 'geht', 'gekannt', 'gekonnt',
    'gemacht', 'gemocht', 'gemusst', 'genug', 'gerade', 'gern', 'gesagt', 'geschweige', 'gewesen',
    'gewollt', 'geworden', 'gibt', 'ging', 'gleich', 'gross', 'grosse', 'grossen', 'grosser',
    'grosses', 'groß', 'große', 'großen', 'großer', 'großes', 'gut', 'gute', 'guter', 'gutes', 'hab',
    'habe', 'haben', 'habt', 'hast', 'hat', 'hatte', 'hatten', 'heisst', 'heißt', 'her', 'heute',
    'hier', 'hin', 'hinter', 'hoch', 'ich', 'ihm', 'ihn', 'ihnen', 'ihr', 'ihre', 'ihrem', 'ihren',
    'ihrer', 'ihres', 'im', 'immer', 'in', 'indem', 'infolgedessen', 'ins', 'irgend', 'ist', 'ja',
    'jahr', 'jahre', 'jahren', 'je', 'jede', 'jedem', 'jeden', 'jeder', 'jedermann', 'jedermanns',
    'jedes', 'jedoch', 'jemand', 'jemandem', 'jemanden', 'jene', 'jenem', 'jenen', 'jener', 'jenes',
    'jetzt', 'kam', 'kann', 'kannst', 'kaum', 'kein', 'keine', 'keinem', 'keinen', 'keiner',
    'keines', 'kleine', 'kleinen', 'kleiner', 'kleines', 'kommen', 'kommt', 'konnen', 'konnt',
    'konnte', 'konnten', 'kurz', 'lang', 'lange', 'leicht', 'leider', 'lieber', 'los', 'machen',
    'macht', 'machte', 'mag', 'magst', 'man', 'manche', 'manchem', 'manchen', 'mancher', 'manches',
    'mehr', 'mein', 'meine', 'meinem', 'meinen', 'meiner', 'meines', 'mich', 'mir', 'mit', 'mittel',
    'mochte', 'mochten', 'mogen', 'moglich', 'mogt', 'morgen', 'muss', 'mussen', 'musst', 'musste',
    'mussten', 'muß', 'na', 'nach', 'nachdem', 'nahm', 'naturlich', 'neben', 'nein', 'neue', 'neuen',
    'neun', 'neunte', 'neunten', 'neunter', 'neuntes', 'nicht', 'nichts', 'nie', 'niemand',
    'niemandem', 'niemanden', 'noch', 'nun', 'nur', 'ob', 'oben', 'oder', 'offen', 'oft', 'ohne',
    'recht', 'rechte', 'rechten', 'rechter', 'rechtes', 'richtig', 'rund', 'sagt', 'sagte', 'sah',
    'satt', 'schlecht', 'schon', 'sechs', 'sechste', 'sechsten', 'sechster', 'sechstes', 'sehr',
    'sei', 'seid', 'seien', 'sein', 'seine', 'seinem', 'seinen', 'seiner', 'seines', 'seit',
    'seitdem', 'selbst', 'sich', 'sie', 'sieben', 'siebente', 'siebenten', 'siebenter', 'siebentes',
    'siebte', 'siebten', 'siebter', 'siebtes', 'sind', 'so', 'solang', 'solche', 'solchem',
    'solchen', 'solcher', 'solches', 'soll', 'sollen', 'sollte', 'sollten', 'sondern', 'sonst',
    'sowie', 'spater', 'statt', 'tag', 'tage', 'tagen', 'tat', 'teil', 'tel', 'trotzdem', 'tun',
    'uber', 'uberhaupt', 'ubrigens', 'uhr', 'um', 'und', 'uns', 'unser', 'unsere', 'unserem',
    'unseren', 'unserer', 'unseres', 'unter', 'vergangene', 'vergangenen', 'viel', 'viele', 'vielem',
    'vielen', 'vielleicht', 'vier', 'vierte', 'vierten', 'vierter', 'viertes', 'vom', 'von', 'vor',
    'wahr', 'wahrend', 'wahrenddem', 'wahrenddessen', 'wann', 'war', 'ware', 'waren', 'warst',
    'wart', 'warum', 'was', 'weg', 'wegen', 'weil', 'weit', 'weiter', 'weitere', 'weiteren',
    'weiteres', 'welche', 'welchem', 'welchen', 'welcher', 'welches', 'wem', 'wen', 'wenig',
    'wenige', 'weniger', 'weniges', 'wenigstens', 'wenn', 'wer', 'werde', 'werden', 'werdet',
    'wessen', 'wie', 'wieder', 'will', 'willst', 'wir', 'wird', 'wirklich', 'wirst', 'wo', 'wohl',
    'wollen', 'wollt', 'wollte', 'wollten', 'worden', 'wurde', 'wurden', 'zehn', 'zehnte', 'zehnten',
    'zehnter', 'zehntes', 'zeit', 'zu', 'zuerst', 'zugleich', 'zum', 'zunachst', 'zur', 'zuruck',
    'zusammen', 'zwanzig', 'zwar', 'zwei', 'zweite', 'zweiten', 'zweiter', 'zweites', 'zwischen',
  ],
  // Dutch (342 words)
  nl: [
    'aan', 'aangaande', 'aangezien', 'achter', 'achterna', 'af', 'afgelopen', 'al', 'aldus',
    'alhoewel', 'alle', 'allebei', 'alleen', 'allen', 'alles', 'als', 'altijd', 'ander', 'andere',
    'anderen', 'anders', 'anderzijds', 'behalve', 'beide', 'beiden', 'ben', 'beneden', 'bent',
    'bepaald', 'beter', 'betere', 'betreffende', 'bij', 'bijna', 'bijvoorbeeld', 'binnen',
    'binnenin', 'boven', 'bovenal', 'bovendien', 'bovenstaand', 'buiten', 'daar', 'daarheen',
    'daarin', 'daarna', 'daarnet', 'daarom', 'daarop', 'dan', 'dat', 'de', 'den', 'der', 'des',
    'deze', 'dezelfde', 'dezen', 'die', 'dien', 'dikwijls', 'dit', 'doch', 'doen', 'doet', 'door',
    'doorgaand', 'doorgaans', 'dus', 'echter', 'een', 'eens', 'eerder', 'eerst', 'eerste', 'eersten',
    'effe', 'eigen', 'elk', 'elke', 'en', 'enige', 'enkel', 'enkele', 'enz', 'er', 'erdoor', 'etc',
    'even', 'eveneens', 'evenwel', 'ff', 'gauw', 'ge', 'gedurende', 'geen', 'gegeven', 'gehad',
    'geheel', 'gekund', 'geleden', 'gelijk', 'gemogen', 'geven', 'geweest', 'gewoon', 'gewoonweg',
    'geworden', 'gij', 'haar', 'had', 'hadden', 'hare', 'heb', 'hebben', 'hebt', 'heeft', 'hele',
    'hem', 'hen', 'het', 'hier', 'hierbeneden', 'hierboven', 'hierin', 'hij', 'hoe', 'hoewel', 'hun',
    'idd', 'ieder', 'iemand', 'iets', 'ik', 'ikke', 'ikzelf', 'in', 'indien', 'inmiddels', 'inz',
    'inzake', 'is', 'ja', 'je', 'jezelf', 'jij', 'jijzelf', 'jou', 'jouw', 'jouwe', 'juist',
    'jullie', 'kan', 'klaar', 'kon', 'konden', 'krachtens', 'kunnen', 'kunt', 'lang', 'later',
    'liet', 'liever', 'maar', 'mag', 'me', 'mede', 'meer', 'meesten', 'men', 'met', 'mezelf', 'mij',
    'mijn', 'mijzelf', 'min', 'minder', 'misschien', 'mocht', 'mochten', 'moest', 'moesten', 'moet',
    'moeten', 'mogelijk', 'mogen', 'na', 'naar', 'nabij', 'nadat', 'net', 'niet', 'niets', 'nog',
    'nogal', 'nooit', 'nr', 'nu', 'of', 'om', 'omdat', 'omhoog', 'omlaag', 'omstreeks', 'omtrent',
    'omver', 'onder', 'ondertussen', 'ongeveer', 'ons', 'onszelf', 'onze', 'ooit', 'ook', 'op',
    'opdat', 'opnieuw', 'opzij', 'over', 'overigens', 'pas', 'pp', 'precies', 'prof', 'publ',
    'reeds', 'rond', 'rondom', 'sedert', 'sinds', 'sindsdien', 'slechts', 'sommige', 'spoedig',
    'steeds', 't', 'tamelijk', 'te', 'tegen', 'ten', 'tenzij', 'ter', 'terwijl', 'thans', 'tijdens',
    'toch', 'toe', 'toen', 'tot', 'totdat', 'tussen', 'u', 'uit', 'uitgezonderd', 'uw', 'uwe',
    'uwen', 'vaak', 'van', 'vanaf', 'vandaan', 'vanuit', 'vanwege', 'veel', 'veeleer', 'verder',
    'verre', 'vervolgens', 'vgl', 'volgens', 'voor', 'vooraf', 'vooral', 'vooralsnog', 'voorbij',
    'voordat', 'voordien', 'voorheen', 'voorop', 'voort', 'voorts', 'vooruit', 'vrij', 'vroeg',
    'waar', 'waarom', 'wanneer', 'want', 'waren', 'was', 'wat', 'we', 'weer', 'weg', 'wegens',
    'weinig', 'weinige', 'wel', 'weldra', 'welk', 'welke', 'welken', 'werd', 'werden', 'wezen',
    'wie', 'wiens', 'wier', 'wij', 'wil', 'wilde', 'worden', 'wordt', 'zal', 'ze', 'zeer', 'zei',
    'zeker', 'zekere', 'zelf', 'zelfde', 'zelfs', 'zich', 'zichzelf', 'zij', 'zijn', 'zijnde',
    'zijne', 'zo', 'zoals', 'zodra', 'zon', 'zonder', 'zou', 'zouden', 'zoveel', 'zowat', 'zulk',
    'zulke', 'zulks', 'zullen', 'zult',
  ],
  // Italian (606 words)
  it: [
    'a', 'abbastanza', 'abbia', 'abbiamo', 'abbiano', 'abbiate', 'accidenti', 'ad', 'adesso',
    'affinche', 'agl', 'agli', 'ahime', 'ai', 'al', 'alcuna', 'alcuni', 'alcuno', 'all', 'alla',
    'alle', 'allo', 'allora', 'altri', 'altrimenti', 'altro', 'altrove', 'altrui', 'anche', 'ancora',
    'anni', 'anno', 'ansa', 'anticipo', 'assai', 'attesa', 'attraverso', 'avanti', 'avemmo',
    'avendo', 'avente', 'aver', 'avere', 'averlo', 'avesse', 'avessero', 'avessi', 'avessimo',
    'aveste', 'avesti', 'avete', 'aveva', 'avevamo', 'avevano', 'avevate', 'avevi', 'avevo', 'avra',
    'avrai', 'avranno', 'avrebbe', 'avrebbero', 'avrei', 'avremmo', 'avremo', 'avreste', 'avresti',
    'avrete', 'avro', 'avuta', 'avute', 'avuti', 'avuto', 'basta', 'bene', 'benissimo', 'brava',
    'bravo', 'c', 'casa', 'caso', 'cento', 'certa', 'certe', 'certi', 'certo', 'che', 'chi',
    'chicchessia', 'chiunque', 'ci', 'ciascuna', 'ciascuno', 'cima', 'cio', 'cioe', 'circa', 'citta',
    'co', 'codesta', 'codesti', 'codesto', 'cogli', 'coi', 'col', 'colei', 'coll', 'coloro', 'colui',
    'come', 'cominci', 'comunque', 'con', 'concernente', 'conciliarsi', 'conclusione', 'consiglio',
    'contro', 'cortesia', 'cos', 'cosa', 'cosi', 'cui', 'd', 'da', 'dagl', 'dagli', 'dai', 'dal',
    'dall', 'dalla', 'dalle', 'dallo', 'dappertutto', 'davanti', 'degl', 'degli', 'dei', 'del',
    'dell', 'della', 'delle', 'dello', 'dentro', 'detto', 'deve', 'di', 'dice', 'dietro', 'dire',
    'dirimpetto', 'diventa', 'diventare', 'diventato', 'dopo', 'dov', 'dove', 'dovra', 'dovunque',
    'due', 'dunque', 'durante', 'e', 'ebbe', 'ebbero', 'ebbi', 'ecc', 'ecco', 'ed', 'effettivamente',
    'egli', 'ella', 'entrambi', 'eppure', 'era', 'erano', 'eravamo', 'eravate', 'eri', 'ero',
    'esempio', 'esse', 'essendo', 'esser', 'essere', 'essi', 'ex', 'fa', 'faccia', 'facciamo',
    'facciano', 'facciate', 'faccio', 'facemmo', 'facendo', 'facesse', 'facessero', 'facessi',
    'facessimo', 'faceste', 'facesti', 'faceva', 'facevamo', 'facevano', 'facevate', 'facevi',
    'facevo', 'fai', 'fanno', 'fara', 'farai', 'faranno', 'fare', 'farebbe', 'farebbero', 'farei',
    'faremmo', 'faremo', 'fareste', 'faresti', 'farete', 'faro', 'fatto', 'favore', 'fece', 'fecero',
    'feci', 'fin', 'finalmente', 'finche', 'fine', 'fino', 'forse', 'forza', 'fosse', 'fossero',
    'fossi', 'fossimo', 'foste', 'fosti', 'fra', 'frattempo', 'fu', 'fui', 'fummo', 'fuori',
    'furono', 'futuro', 'generale', 'gia', 'giacche', 'giorni', 'giorno', 'gl', 'gli', 'gliela',
    'gliele', 'glieli', 'glielo', 'gliene', 'governo', 'grande', 'grazie', 'gruppo', 'ha', 'haha',
    'hai', 'hanno', 'ho', 'i', 'ieri', 'il', 'improvviso', 'in', 'inc', 'infatti', 'inoltre',
    'insieme', 'intanto', 'intorno', 'invece', 'io', 'l', 'la', 'lasciato', 'lato', 'lavoro', 'le',
    'lei', 'li', 'lo', 'lontano', 'loro', 'lui', 'lungo', 'luogo', 'm', 'ma', 'macche', 'magari',
    'maggior', 'mai', 'male', 'malgrado', 'malissimo', 'mancanza', 'marche', 'me', 'medesimo',
    'mediante', 'meglio', 'meno', 'mentre', 'mesi', 'mezzo', 'mi', 'mia', 'mie', 'miei', 'mila',
    'miliardi', 'milioni', 'minimi', 'ministro', 'mio', 'modo', 'molti', 'moltissimo', 'molto',
    'momento', 'mondo', 'mosto', 'nazionale', 'ne', 'negl', 'negli', 'nei', 'nel', 'nell', 'nella',
    'nelle', 'nello', 'nemmeno', 'neppure', 'nessun', 'nessuna', 'nessuno', 'nient', 'niente', 'no',
    'noi', 'non', 'nondimeno', 'nonostante', 'nonsia', 'nostra', 'nostre', 'nostri', 'nostro',
    'novanta', 'nove', 'nulla', 'nuovo', 'o', 'od', 'oggi', 'ogni', 'ognuna', 'ognuno', 'oltre',
    'oppure', 'ora', 'ore', 'osi', 'ossia', 'ottanta', 'otto', 'paese', 'parecchi', 'parecchie',
    'parecchio', 'parte', 'partendo', 'peccato', 'peggio', 'per', 'perche', 'percio', 'perfino',
    'pero', 'persino', 'persone', 'piedi', 'pieno', 'piglia', 'piu', 'piuttosto', 'po', 'pochissimo',
    'poco', 'poi', 'poiche', 'possa', 'possedere', 'posteriore', 'posto', 'potrebbe',
    'preferibilmente', 'presa', 'press', 'prima', 'primo', 'principalmente', 'probabilmente',
    'proprio', 'puo', 'pure', 'purtroppo', 'qualche', 'qualcosa', 'qualcuna', 'qualcuno', 'quale',
    'quali', 'qualunque', 'quando', 'quanta', 'quante', 'quanti', 'quanto', 'quantunque', 'quasi',
    'quattro', 'quel', 'quella', 'quelle', 'quelli', 'quello', 'quest', 'questa', 'queste', 'questi',
    'questo', 'qui', 'quindi', 'realmente', 'recente', 'recentemente', 'registrazione', 'relativo',
    'riecco', 's', 'salvo', 'sara', 'sarai', 'saranno', 'sarebbe', 'sarebbero', 'sarei', 'saremmo',
    'saremo', 'sareste', 'saresti', 'sarete', 'saro', 'scola', 'scopo', 'scorso', 'se', 'secondo',
    'seguente', 'seguito', 'sei', 'sembra', 'sembrare', 'sembrato', 'sembri', 'sempre', 'senza',
    'sette', 'si', 'sia', 'siamo', 'siano', 'siate', 'siete', 'sig', 'solito', 'solo', 'soltanto',
    'sono', 'sopra', 'sotto', 'spesso', 'srl', 'sta', 'stai', 'stando', 'stanno', 'stara', 'starai',
    'staranno', 'starebbe', 'starebbero', 'starei', 'staremmo', 'staremo', 'stareste', 'staresti',
    'starete', 'staro', 'stata', 'state', 'stati', 'stato', 'stava', 'stavamo', 'stavano', 'stavate',
    'stavi', 'stavo', 'stemmo', 'stessa', 'stesse', 'stessero', 'stessi', 'stessimo', 'stesso',
    'steste', 'stesti', 'stette', 'stettero', 'stetti', 'stia', 'stiamo', 'stiano', 'stiate', 'sto',
    'su', 'sua', 'subito', 'successivamente', 'successivo', 'sue', 'sugl', 'sugli', 'sui', 'sul',
    'sull', 'sulla', 'sulle', 'sullo', 'suo', 'suoi', 't', 'tale', 'tali', 'talvolta', 'tanto', 'te',
    'tempo', 'ti', 'titolo', 'tra', 'tranne', 'tre', 'trenta', 'troppo', 'trovato', 'tu', 'tua',
    'tue', 'tuo', 'tuoi', 'tutta', 'tuttavia', 'tutte', 'tutti', 'tutto', 'uguali', 'ulteriore',
    'ultimo', 'un', 'una', 'uno', 'uomo', 'v', 'va', 'vale', 'vari', 'varia', 'varie', 'vario',
    'verso', 'vi', 'via', 'vicino', 'visto', 'vita', 'voi', 'volta', 'volte', 'vostra', 'vostre',
    'vostri', 'vostro',
  ],
  // Spanish (605 words)
  es: [
    'a', 'acuerdo', 'adelante', 'ademas', 'afirmo', 'agrego', 'ahi', 'ahora', 'al', 'algo',
    'algun', 'alguna', 'algunas', 'alguno', 'algunos', 'alli', 'alrededor', 'ambos', 'anadio',
    'ante', 'anterior', 'antes', 'apenas', 'aproximadamente', 'aquel', 'aquella', 'aquellas',
    'aquello', 'aquellos', 'aqui', 'arriba', 'aseguro', 'asi', 'atras', 'aun', 'aunque', 'bajo',
    'bastante', 'bien', 'breve', 'buen', 'buena', 'buenas', 'bueno', 'buenos', 'cada', 'casi',
    'cierta', 'ciertas', 'cierto', 'ciertos', 'cinco', 'claro', 'comento', 'como', 'con', 'conmigo',
    'conocer', 'conseguimos', 'conseguir', 'considera', 'considero', 'consigo', 'consigue',
    'consiguen', 'consigues', 'contigo', 'contra', 'creo', 'cual', 'cuales', 'cualquier', 'cuando',
    'cuanta', 'cuantas', 'cuanto', 'cuantos', 'cuatro', 'cuenta', 'da', 'dado', 'dan', 'dar', 'de',
    'debajo', 'debe', 'deben', 'debido', 'decir', 'dejo', 'del', 'delante', 'demas', 'demasiado',
    'dentro', 'deprisa', 'desde', 'despacio', 'despues', 'detras', 'dia', 'dias', 'dice', 'dicen',
    'dicho', 'dieron', 'diez', 'diferente', 'diferentes', 'dijeron', 'dijo', 'dio', 'doce', 'donde',
    'dos', 'durante', 'e', 'el', 'ella', 'ellas', 'ello', 'ellos', 'embargo', 'en', 'encima',
    'encuentra', 'enfrente', 'enseguida', 'entonces', 'entre', 'era', 'erais', 'eramos', 'eran',
    'eras', 'eres', 'es', 'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'estaba', 'estabais',
    'estabamos', 'estaban', 'estabas', 'estad', 'estada', 'estadas', 'estado', 'estados', 'estais',
    'estamos', 'estan', 'estando', 'estar', 'estara', 'estaran', 'estaras', 'estare', 'estareis',
    'estaremos', 'estaria', 'estariais', 'estariamos', 'estarian', 'estarias', 'estas', 'este',
    'esteis', 'estemos', 'esten', 'estes', 'esto', 'estos', 'estoy', 'estuve', 'estuviera',
    'estuvierais', 'estuvieramos', 'estuvieran', 'estuvieras', 'estuvieron', 'estuviese',
    'estuvieseis', 'estuviesemos', 'estuviesen', 'estuvieses', 'estuvimos', 'estuviste',
    'estuvisteis', 'estuvo', 'excepto', 'existe', 'existen', 'explico', 'expreso', 'fin', 'final',
    'fue', 'fuera', 'fuerais', 'fueramos', 'fueran', 'fueras', 'fueron', 'fuese', 'fueseis',
    'fuesemos', 'fuesen', 'fueses', 'fui', 'fuimos', 'fuiste', 'fuisteis', 'gran', 'grande',
    'grandes', 'ha', 'habeis', 'haber', 'habia', 'habiais', 'habiamos', 'habian', 'habias', 'habida',
    'habidas', 'habido', 'habidos', 'habiendo', 'habla', 'hablan', 'habra', 'habran', 'habras',
    'habre', 'habreis', 'habremos', 'habria', 'habriais', 'habriamos', 'habrian', 'habrias', 'hace',
    'haceis', 'hacemos', 'hacen', 'hacer', 'hacerlo', 'haces', 'hacia', 'haciendo', 'hago', 'han',
    'has', 'hasta', 'hay', 'haya', 'hayais', 'hayamos', 'hayan', 'hayas', 'he', 'hecho', 'hemos',
    'hicieron', 'hizo', 'hoy', 'hube', 'hubiera', 'hubierais', 'hubieramos', 'hubieran', 'hubieras',
    'hubieron', 'hubiese', 'hubieseis', 'hubiesemos', 'hubiesen', 'hubieses', 'hubimos', 'hubiste',
    'hubisteis', 'hubo', 'igual', 'incluso', 'indico', 'informo', 'ir', 'junto', 'la', 'lado',
    'largo', 'las', 'le', 'les', 'llego', 'lleva', 'llevar', 'lo', 'los', 'luego', 'mal', 'manera',
    'manifesto', 'mas', 'mayor', 'me', 'mediante', 'medio', 'mejor', 'menciono', 'menos', 'menudo',
    'mi', 'mia', 'mias', 'mientras', 'mio', 'mios', 'mis', 'misma', 'mismas', 'mismo', 'mismos',
    'modo', 'mucha', 'muchas', 'mucho', 'muchos', 'muy', 'nada', 'nadie', 'ni', 'ningun', 'ninguna',
    'ningunas', 'ninguno', 'ningunos', 'no', 'nos', 'nosotras', 'nosotros', 'nuestra', 'nuestras',
    'nuestro', 'nuestros', 'nueva', 'nuevas', 'nueve', 'nuevo', 'nuevos', 'nunca', 'o', 'ocho',
    'once', 'os', 'otra', 'otras', 'otro', 'otros', 'pais', 'para', 'parece', 'parte', 'partir',
    'pasada', 'pasado', 'peor', 'pero', 'pesar', 'poca', 'pocas', 'poco', 'pocos', 'podeis',
    'podemos', 'poder', 'podra', 'podran', 'podria', 'podriais', 'podriamos', 'podrian', 'podrias',
    'poner', 'por', 'porque', 'posible', 'primer', 'primera', 'primero', 'primeros', 'pronto',
    'propia', 'propias', 'propio', 'propios', 'proximo', 'proximos', 'pudo', 'pueda', 'puede',
    'pueden', 'puedo', 'pues', 'qeu', 'que', 'quedo', 'queremos', 'quien', 'quienes', 'quiere',
    'quiza', 'quizas', 'realizado', 'realizar', 'realizo', 'repente', 'respecto', 'sabe', 'sabeis',
    'sabemos', 'saben', 'saber', 'sabes', 'salvo', 'se', 'sea', 'seais', 'seamos', 'sean', 'seas',
    'segun', 'segunda', 'segundo', 'seis', 'senalo', 'sentid', 'sentida', 'sentidas', 'sentido',
    'sentidos', 'ser', 'sera', 'seran', 'seras', 'sere', 'sereis', 'seremos', 'seria', 'seriais',
    'seriamos', 'serian', 'serias', 'si', 'sido', 'siempre', 'siendo', 'siente', 'siete', 'sigue',
    'siguiente', 'sin', 'sino', 'sintiendo', 'sobre', 'sois', 'sola', 'solamente', 'solas', 'solo',
    'solos', 'somos', 'son', 'soy', 'su', 'supuesto', 'sus', 'suya', 'suyas', 'suyo', 'suyos', 'tal',
    'tambien', 'tampoco', 'tan', 'tanto', 'tarde', 'te', 'temprano', 'tendra', 'tendran', 'tendras',
    'tendre', 'tendreis', 'tendremos', 'tendria', 'tendriais', 'tendriamos', 'tendrian', 'tendrias',
    'tened', 'teneis', 'tenemos', 'tener', 'tenga', 'tengais', 'tengamos', 'tengan', 'tengas',
    'tengo', 'tenia', 'teniais', 'teniamos', 'tenian', 'tenias', 'tenida', 'tenidas', 'tenido',
    'tenidos', 'teniendo', 'tercera', 'tercero', 'ti', 'tiene', 'tienen', 'tienes', 'toda', 'todas',
    'todavia', 'todo', 'todos', 'total', 'tras', 'trata', 'traves', 'tres', 'tu', 'tus', 'tuve',
    'tuviera', 'tuvierais', 'tuvieramos', 'tuvieran', 'tuvieras', 'tuvieron', 'tuviese', 'tuvieseis',
    'tuviesemos', 'tuviesen', 'tuvieses', 'tuvimos', 'tuviste', 'tuvisteis', 'tuvo', 'tuya', 'tuyas',
    'tuyo', 'tuyos', 'u', 'ultima', 'ultimas', 'ultimo', 'ultimos', 'un', 'una', 'unas', 'uno',
    'unos', 'usa', 'usais', 'usamos', 'usan', 'usar', 'usas', 'uso', 'usted', 'ustedes', 'va',
    'vais', 'vamos', 'van', 'varias', 'varios', 'vaya', 'veces', 'ver', 'verdad', 'verdadera',
    'verdadero', 'vez', 'vosotras', 'vosotros', 'voy', 'vuestra', 'vuestras', 'vuestro', 'vuestros',
    'y', 'ya', 'yo',
  ],
  // Hebrew (213 words)
  he: [
    'אבל', 'או', 'אולי', 'אותה', 'אותו', 'אותי', 'אותך', 'אותם', 'אותן', 'אותנו', 'אז', 'אחר',
    'אחרות', 'אחרי', 'אחרים', 'אחרת', 'אי', 'איזה', 'איך', 'אין', 'איפה', 'איתה', 'איתו', 'איתי',
    'איתך', 'איתכם', 'איתכן', 'איתם', 'איתן', 'איתנו', 'אך', 'אל', 'אלה', 'אלו', 'אם', 'אנחנו',
    'אני', 'אס', 'אף', 'אצל', 'אשר', 'את', 'אתה', 'אתכם', 'אתכן', 'אתם', 'אתן', 'באיזו', 'באיזומידה',
    'באמצע', 'באמצעות', 'בגלל', 'בו', 'בין', 'בלי', 'במידה', 'במקום', 'במקוםשבו', 'בעד', 'ברם',
    'בשביל', 'בשעה', 'בשעהש', 'בתוך', 'גם', 'דרך', 'הוא', 'היא', 'היה', 'הייתי', 'היכן', 'היתה',
    'היתי', 'הם', 'הן', 'הנה', 'הסיבה', 'הסיבהשבגללה', 'הרי', 'ואילו', 'ואת', 'זאת', 'זה', 'זות',
    'יהיה', 'יוכל', 'יוכלו', 'יותר', 'יכול', 'יכולה', 'יכולות', 'יכולים', 'יכל', 'יכלה', 'יכלו',
    'יש', 'כאן', 'כאשר', 'כולם', 'כולן', 'כזאת', 'כזה', 'כי', 'כיצד', 'כך', 'ככה', 'כל', 'כלל',
    'כמו', 'כן', 'כפי', 'כש', 'לא', 'לאו', 'לאיזו', 'לאיזותכלית', 'לאן', 'לבין', 'לה', 'להיות',
    'להם', 'להן', 'לו', 'לי', 'לכם', 'לכן', 'למה', 'למטה', 'למעלה', 'למקום', 'למקוםשבו', 'למרות',
    'לנו', 'לעבר', 'לעיכן', 'לפיכך', 'לפני', 'מאד', 'מאוד', 'מאחורי', 'מאיזו', 'מאיזוסיבה', 'מאין',
    'מאיפה', 'מבלי', 'מבעד', 'מדוע', 'מדי', 'מה', 'מהיכן', 'מול', 'מחוץ', 'מי', 'מידה', 'מכאן',
    'מכיוון', 'מלבד', 'מן', 'מנין', 'מסוגל', 'מעט', 'מעטים', 'מעל', 'מצד', 'מקום', 'מקוםבו', 'מתחת',
    'מתי', 'נגד', 'נגר', 'נו', 'סיבה', 'עד', 'עז', 'על', 'עלי', 'עליה', 'עליהם', 'עליהן', 'עליו',
    'עליך', 'עליכם', 'עליכן', 'עלינו', 'עם', 'עצמה', 'עצמהם', 'עצמהן', 'עצמו', 'עצמי', 'עצמם',
    'עצמן', 'עצמנו', 'פה', 'רק', 'ש', 'שבגללה', 'שבו', 'שוב', 'של', 'שלה', 'שלהם', 'שלהן', 'שלו',
    'שלי', 'שלך', 'שלכם', 'שלכן', 'שלנו', 'שם', 'תהיה', 'תחת', 'תכלית',
  ],
  // Arabic (725 words)
  ar: [
    'ء', 'ا', 'اب', 'ابتدا', 'ابدا', 'ابريل', 'ابن', 'ابو', 'اتخذ', 'اثنا', 'اثناء', 'اثنان',
    'اثني', 'اثنين', 'اجل', 'اجمع', 'احد', 'احدى', 'اخ', 'اخبر', 'اخذ', 'اخلولق', 'اخو', 'اذ', 'اذا',
    'اذار', 'اذما', 'اذن', 'اربع', 'اربعاء', 'اربعة', 'اربعماية', 'اربعمية', 'اربعون', 'اربعين',
    'ارتد', 'ارى', 'ازاء', 'استحال', 'اسكن', 'اصبح', 'اصلا', 'اض', 'اضحى', 'اطعم', 'اعطى', 'اعلم',
    'اغسطس', 'اف', 'افريل', 'افعلبه', 'اقبل', 'اقل', 'اكتوبر', 'اكثر', 'ال', 'الا', 'الالاء',
    'الالى', 'الان', 'التي', 'الحالي', 'الذى', 'الذي', 'الذين', 'الف', 'الفى', 'اللاتي', 'اللايي',
    'اللتان', 'اللتي', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'الى', 'الي', 'اليك',
    'اليكم', 'اليكما', 'اليكن', 'اليه', 'اليها', 'اليوم', 'ام', 'اما', 'امام', 'امامك', 'امد', 'امس',
    'امسى', 'امين', 'ان', 'انا', 'اناء', 'انبا', 'انبرى', 'انت', 'انتم', 'انتما', 'انتن', 'انشا',
    'انفا', 'انقلب', 'انما', 'انه', 'انهم', 'انى', 'اه', 'اها', 'اهلا', 'او', 'اوت', 'اوشك', 'اول',
    'اولاء', 'اولالك', 'اوليك', 'اوه', 'اى', 'اي', 'ايا', 'ايار', 'اياك', 'اياكم', 'اياكما', 'اياكن',
    'ايان', 'ايانا', 'اياه', 'اياها', 'اياهم', 'اياهما', 'اياهن', 'اياي', 'ايضا', 'ايلول', 'اين',
    'اينما', 'ايه', 'ايها', 'ب', 'باء', 'بات', 'باللتي', 'بان', 'بتلك', 'بحيث', 'بخ', 'بد', 'بدلا',
    'بذلك', 'بس', 'بضع', 'بطان', 'بعد', 'بعدا', 'بعض', 'بغتة', 'بك', 'بكم', 'بكما', 'بكن', 'بل',
    'بلا', 'بله', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهذا', 'بهذه', 'بهم', 'بهما',
    'بهن', 'بوسا', 'بي', 'بيد', 'بيس', 'بين', 'بينما', 'بيننا', 'بينهم', 'بينهن', 'ة', 'ت', 'تاء',
    'تارة', 'تاسع', 'تان', 'تانك', 'تبدل', 'تجاه', 'تحت', 'تحول', 'تخذ', 'ترك', 'تسع', 'تسعة',
    'تسعماية', 'تسعمية', 'تسعون', 'تسعين', 'تشرين', 'تعسا', 'تعلم', 'تفعلان', 'تفعلون', 'تفعلين',
    'تكون', 'تلقاء', 'تلك', 'تلكم', 'تلكما', 'تموز', 'ته', 'تي', 'تين', 'تينك', 'ث', 'ثاء', 'ثالث',
    'ثامن', 'ثان', 'ثاني', 'ثلاث', 'ثلاثاء', 'ثلاثة', 'ثلاثماية', 'ثلاثمية', 'ثلاثون', 'ثلاثين',
    'ثم', 'ثمان', 'ثمانمية', 'ثمانون', 'ثماني', 'ثمانية', 'ثمانين', 'ثمة', 'ثمنمية', 'ج', 'جانفي',
    'جدا', 'جعل', 'جلل', 'جمعة', 'جميع', 'جنيه', 'جوان', 'جويلية', 'جير', 'جيم', 'ح', 'حاء', 'حادي',
    'حار', 'حاشا', 'حاي', 'حبذا', 'حبيب', 'حتى', 'حجا', 'حدث', 'حذار', 'حرى', 'حزيران', 'حسب', 'حقا',
    'حم', 'حمدا', 'حمو', 'حول', 'حي', 'حيث', 'حيثما', 'حين', 'خ', 'خاء', 'خاصة', 'خال', 'خامس',
    'خبر', 'خلا', 'خلافا', 'خلف', 'خمس', 'خمسة', 'خمسماية', 'خمسمية', 'خمسون', 'خمسين', 'خميس', 'د',
    'دال', 'درهم', 'درى', 'دواليك', 'دولار', 'دون', 'دونك', 'ديسمبر', 'دينار', 'ذ', 'ذا', 'ذات',
    'ذاك', 'ذال', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذهب', 'ذو', 'ذوا', 'ذواتا',
    'ذواتي', 'ذي', 'ذيت', 'ذين', 'ذينك', 'ر', 'راء', 'رابع', 'راح', 'راى', 'رب', 'رجع', 'رزق',
    'رويدك', 'ريال', 'ريث', 'ز', 'زاي', 'زعم', 'زود', 'س', 'ساء', 'سابع', 'سادس', 'سبت', 'سبتمبر',
    'سبحان', 'سبع', 'سبعة', 'سبعماية', 'سبعمية', 'سبعون', 'سبعين', 'ست', 'ستة', 'ستكون', 'ستماية',
    'ستمية', 'ستون', 'ستين', 'سحقا', 'سرا', 'سرعان', 'سقى', 'سمعا', 'سنتيم', 'سوف', 'سوى', 'سين',
    'ش', 'شباط', 'شبه', 'شتان', 'شرع', 'شمال', 'شيكل', 'شين', 'ص', 'صاد', 'صار', 'صباح', 'صبر',
    'صبرا', 'صدقا', 'صراحة', 'صه', 'ض', 'ضاد', 'ضحوة', 'ضد', 'ضمن', 'ط', 'طاء', 'طاق', 'طالما',
    'طرا', 'طفق', 'طق', 'ظ', 'ظاء', 'ظل', 'ظن', 'ع', 'عاد', 'عاشر', 'عامة', 'عجبا', 'عد', 'عدا',
    'عدس', 'عسى', 'عشر', 'عشرة', 'عشرون', 'عشرين', 'عل', 'علق', 'علم', 'على', 'علي', 'عليك', 'عليه',
    'عليها', 'عما', 'عن', 'عند', 'عنه', 'عنها', 'عوض', 'عيانا', 'عين', 'غ', 'غادر', 'غالبا', 'غدا',
    'غداة', 'غير', 'غين', 'ف', 'فاء', 'فاذا', 'فاللتي', 'فان', 'فانه', 'فبراير', 'فرادى', 'فضلا',
    'فقد', 'فقط', 'فكان', 'فلا', 'فلان', 'فلس', 'فمن', 'فهو', 'فو', 'فوق', 'في', 'فيفري', 'فيم',
    'فيما', 'فيه', 'فيها', 'فيهم', 'ق', 'قاطبة', 'قاف', 'قال', 'قالت', 'قام', 'قبل', 'قد', 'قرش',
    'قط', 'قلما', 'ك', 'كاد', 'كاف', 'كان', 'كانت', 'كانما', 'كانون', 'كاي', 'كاين', 'كثيرا', 'كخ',
    'كذا', 'كذلك', 'كرب', 'كسا', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم',
    'كما', 'كن', 'كى', 'كي', 'كيت', 'كيف', 'كيفما', 'ل', 'لا', 'لات', 'لازال', 'لاسيما', 'لام',
    'لان', 'لايزال', 'لبيك', 'لدن', 'لدى', 'لدي', 'لذا', 'لذلك', 'لست', 'لستم', 'لستما', 'لستن',
    'لسن', 'لسنا', 'لسوف', 'لعل', 'لعمر', 'لقد', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكنه', 'لكي',
    'لكيلا', 'لم', 'لما', 'لماذا', 'لن', 'لنا', 'له', 'لها', 'لهذا', 'لهم', 'لهما', 'لهن', 'لو',
    'لولا', 'لوما', 'لي', 'ليت', 'ليرة', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'لين', 'م', 'ما',
    'ماافعله', 'ماانفك', 'مابرح', 'مادام', 'ماذا', 'مارس', 'مازال', 'مافتي', 'ماي', 'ماية', 'مايزال',
    'مايو', 'متى', 'مثل', 'مثلا', 'مذ', 'مرة', 'مساء', 'مع', 'معاذ', 'معه', 'مكانك', 'مكانكم',
    'مكانكما', 'مكانكن', 'مليم', 'مما', 'ممن', 'من', 'منذ', 'منه', 'منها', 'مه', 'مهما', 'مية',
    'ميتان', 'ميم', 'ن', 'نا', 'نبا', 'نحن', 'نحو', 'نخ', 'نعم', 'نفس', 'نوفمبر', 'نون', 'نيسان',
    'نيف', 'ه', 'ها', 'هاء', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هب', 'هج', 'هذا',
    'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هللة', 'هلم', 'هم', 'هما', 'همزة', 'هن',
    'هنا', 'هناك', 'هنالك', 'هو', 'هولاء', 'هي', 'هيا', 'هيت', 'هيهات', 'و', 'وا', 'وابو', 'واثناء',
    'واحد', 'واذ', 'واذا', 'والتي', 'والذي', 'والذين', 'واللتي', 'والى', 'وان', 'واها', 'واو',
    'وايضا', 'وبما', 'وبين', 'وبينما', 'وبينهم', 'وثي', 'وجد', 'وراءك', 'ورد', 'وسوف', 'وشكان',
    'وعلى', 'وفي', 'وقبل', 'وقد', 'وكان', 'وكانت', 'وكذلك', 'وكل', 'ولا', 'ولايزال', 'ولذا', 'ولسوف',
    'ولعل', 'ولقد', 'ولكن', 'ولم', 'ولما', 'ولماذا', 'وله', 'ولهذا', 'ولو', 'وليس', 'وليست', 'وما',
    'وماذا', 'ومع', 'ومن', 'ومنها', 'وهب', 'وهذا', 'وهل', 'وهو', 'وهي', 'وي', 'ى', 'ي', 'يا', 'ياء',
    'يفعلان', 'يفعلون', 'يكون', 'يلي', 'يمكن', 'يمين', 'ين', 'يناير', 'يوان', 'يورو', 'يوليو', 'يوم',
    'يونيو',
  ],
};

const stopwordSets = new Map<string, Set<string>>();

function getStopwordSet(languageCode: string): Set<string> {
  if (stopwordSets.has(languageCode)) {
    return stopwordSets.get(languageCode)!;
  }

  const words = STOPWORDS[languageCode] ?? [];
  const set = new Set(words);
  stopwordSets.set(languageCode, set);
  return set;
}

/**
 * Check if a word is a stopword in the given language.
 */
export function isStopword(word: string, languageCode: string): boolean {
  return getStopwordSet(languageCode).has(word);
}

/**
 * Filter out stopwords from a word list.
 */
export function removeStopwords(words: string[], languageCode: string): string[] {
  const set = getStopwordSet(languageCode);
  return words.filter((w) => !set.has(w));
}
